basePath: /
definitions:
  models.User:
    properties:
      email:
        description: Ensures the email field is unique and limited to 100 characters.
        type: string
      id:
        description: Primary key with auto-increment.
        type: integer
      is_active:
        description: Sets default value to true, indicating the user is active by
          default.
        type: boolean
      name:
        description: Limits the name field to 100 characters for efficient database
          usage.
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - users
swagger: "2.0"
