# Use the official Golang image as the base
FROM golang:1.23
#RUN go get -u github.com/cosmtrek/air
# Set the working directory inside the container
WORKDIR /app

# Install air for hot-reloading
RUN go install github.com/air-verse/air@latest

# Copy the source code into the container
COPY go.mod go.sum ./
# Download and install dependencies
RUN go mod download

COPY . .

# Expose the application port
EXPOSE 8080

# Set the command to run the application
CMD ["air"]

