version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: "app_postgres"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  influxdb:
    image: influxdb:latest
    container_name: "app_influxdb"
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
