services:
  go_app:
    container_name: go_app
    # Build the Docker image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_URL: "${REDIS_URL}"
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_TOKEN: "${INFLUXDB_TOKEN}"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the current directory to /app inside the container
    command: ["air"]
    depends_on:
      - go_db
      - go_redis
      - go_influxdb

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  go_redis:
    container_name: go_redis
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  go_influxdb:
    container_name: go_influxdb
    image: influxdb:2.0
    environment:
      INFLUXDB_DB: "${INFLUXDB_DB}"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
    ports:
      - "8086:8086"
    volumes:
      - influxdbdata:/var/lib/influxdb

volumes:
  pgdata: { }
  redisdata: { }
  influxdbdata: { }
